version: '3' 
services:
  jdk-tomcat:
    image: openkbs/jdk-tomcat
    build:
      context: ./Dockerfile
    container_name: jdk-tomcat
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./workspace:/home/developer/workspace

