version: '3' 
services:
  jdk-tomcat:
    image: openkbs/jdk-tomcat
    build:
      context: ./Dockerfile
    container_name: jdk-tomcat
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
    ports:
      - 18880:8080
      - 18443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace

